In [1]:
# Demonstration of TensorFlow and PyTorch
# ----------------------------------------
# AIM: Demonstrate use of TensorFlow and PyTorch by implementing simple code in Python

# 🔹 TensorFlow Section
import tensorflow as tf
import numpy as np

print("=== TensorFlow Demo ===")
# Create random tensors
a = tf.random.uniform((3, 3), minval=1, maxval=10, dtype=tf.int32)
b = tf.random.uniform((3, 3), minval=1, maxval=10, dtype=tf.int32)

print("Tensor A:\n", a.numpy())
print("Tensor B:\n", b.numpy())

# Basic operations
print("\nAddition:\n", tf.add(a, b).numpy())
print("Subtraction:\n", tf.subtract(a, b).numpy())
print("Element-wise Multiplication:\n", tf.multiply(a, b).numpy())
print("Matrix Multiplication:\n", tf.matmul(a, b).numpy())
print("Division:\n", tf.divide(tf.cast(a, tf.float32), tf.cast(b, tf.float32)).numpy())

# Extra operations
print("\nTranspose of A:\n", tf.transpose(a).numpy())
print("Mean of A:", tf.reduce_mean(tf.cast(a, tf.float32)).numpy())
print("Max of B:", tf.reduce_max(b).numpy())

# Broadcasting example
c = tf.constant([1, 2, 3])
print("\nBroadcasted Addition:\n", a + c)

# Reshape and slicing
arr = tf.constant(np.arange(1, 10), shape=(3, 3))
print("\nOriginal Tensor:\n", arr.numpy())
print("Sliced [0:2, 1:3]:\n", arr[0:2, 1:3].numpy())

# Gradient computation
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 5*x + 2
grad = tape.gradient(y, x)
print("\nGradient of y = x² + 5x + 2 at x=3:", grad.numpy())


# 🔹 PyTorch Section
import torch

print("\n=== PyTorch Demo ===")
# Create random tensors
A = torch.randint(1, 10, (3, 3))
B = torch.randint(1, 10, (3, 3))

print("Tensor A:\n", A)
print("Tensor B:\n", B)

# Basic operations
print("\nAddition:\n", A + B)
print("Subtraction:\n", A - B)
print("Element-wise Multiplication:\n", A * B)
print("Matrix Multiplication:\n", torch.mm(A, B))
print("Division:\n", A.float() / B.float())

# Extra operations
print("\nTranspose of A:\n", A.T)
print("Mean of A:", A.float().mean().item())
print("Max of B:", B.max().item())

# Broadcasting example
c = torch.tensor([1, 2, 3])
print("\nBroadcasted Addition:\n", A + c)

# Reshape and slicing
C = torch.arange(1, 10).reshape(3, 3)
print("\nOriginal Tensor:\n", C)
print("Sliced [0:2, 1:3]:\n", C[0:2, 1:3])

# Gradient computation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 5*x + 2
y.backward()
print("\nGradient of y = x² + 5x + 2 at x=3:", x.grad.item())


=== TensorFlow Demo ===
Tensor A:
 [[7 4 6]
 [2 3 1]
 [1 1 4]]
Tensor B:
 [[5 6 5]
 [4 3 6]
 [1 9 4]]

Addition:
 [[12 10 11]
 [ 6  6  7]
 [ 2 10  8]]
Subtraction:
 [[ 2 -2  1]
 [-2  0 -5]
 [ 0 -8  0]]
Element-wise Multiplication:
 [[35 24 30]
 [ 8  9  6]
 [ 1  9 16]]
Matrix Multiplication:
 [[ 57 108  83]
 [ 23  30  32]
 [ 13  45  27]]
Division:
 [[1.4        0.6666667  1.2       ]
 [0.5        1.         0.16666667]
 [1.         0.11111111 1.        ]]

Transpose of A:
 [[7 2 1]
 [4 3 1]
 [6 1 4]]
Mean of A: 3.2222223
Max of B: 9

Broadcasted Addition:
 tf.Tensor(
[[8 6 9]
 [3 5 4]
 [2 3 7]], shape=(3, 3), dtype=int32)

Original Tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced [0:2, 1:3]:
 [[2 3]
 [5 6]]

Gradient of y = x² + 5x + 2 at x=3: 11.0

=== PyTorch Demo ===
Tensor A:
 tensor([[6, 4, 5],
        [4, 1, 5],
        [8, 4, 1]])
Tensor B:
 tensor([[3, 8, 2],
        [4, 6, 6],
        [1, 3, 4]])

Addition:
 tensor([[ 9, 12,  7],
        [ 8,  7, 11],
        [ 9,  7,  5]])
Subtract